### ISSUE TITLE
Plugin version is not displayed properly in flake8 --version output

### ISSUE THREAD

**Issue by svisser** [rubik/radon#105]
`flake8` prints `<property object at 0x.........>` rather than `1.4.2` when `flake8 --version` is called.

Steps to reproduce:

    pip install flake8==3.3.0 radon==1.4.2
    flake8 --version

gives:

    3.3.0 (mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.5.0, radon: <property object at 0x1092c0d08>) CPython 2.7.10 on Darwin

**Comment by rubik** [comment]
Thanks for the report, I had never noticed this.

**Comment by svisser** [comment]
Thank you!
