### ISSUE TITLE
Include missing files in MANIFEST.in

### ISSUE THREAD

**Issue by SpotlightKid** [rubik/radon#107]
To help packing radon for distributions, could you please include the following files in `MANIFEST.in` so that they get included in the source distribution:

* `LICENSE`
* `CHANGELOG` (referenced by `docs/changelog.rst`)

(For context, I'm maintaining https://aur.archlinux.org/packages/python-radon/)

**Comment by rubik** [comment]
Done. Thanks a lot for maintaining the AUR package!

**Comment by SpotlightKid** [comment]
Thanks. Unfortunately, I can't update the AUR package to the latest version at the moment, because the python-bleach package is out-of-date and still at 1.5.x. Will update asap.

**Comment by SpotlightKid** [comment]
Ups, sorry, I was thinking about the `readme_renderer` AUR packeg, not `radon`. please disregard my comment.
