### ISSUE TITLE
Handle string interpolation in Python 3.6

### ISSUE THREAD

**Issue by twschiller** [rubik/radon#108]
Radon reports interpolated strings (f-strings) as syntax errors when running on Python 3.6 code.

Syntax: [PEP 498](https://www.python.org/dev/peps/pep-0498/)

**Comment by rubik** [comment]
Syntax errors are not possible, because Radon leverages Python's AST parser. Therefore the only possible explanation is that you're running Radon with a version of Python that does not support interpolated strings. Maybe it's version 3.5?

**Comment by twschiller** [comment]
Got it. I'm seeing the error on Code Climate, so will follow up with them.

Code Climate Radon Docs, for reference: https://docs.codeclimate.com/v1.0/docs/radon

**Comment by rubik** [comment]
Ah I see. The docker image should be using Alpine Linux, which as far as I know still does not support Python 3.6:
https://github.com/jfloff/alpine-python
