### ISSUE TITLE
LOC is not showing the actual Physical Lines of Code

### ISSUE THREAD

**Issue by zukoj** [rubik/radon#109]
sloc+blank=loc does not hold

Currently:
LOC = the actual Physical LOC - Single comments - Blank (As is shown in the attached file)

[Error log.txt](https://github.com/rubik/radon/files/884091/Error.log.txt)

**Comment by rubik** [comment]
This has probably something to do with the recent PR regarding raw metrics. I'll have a look into it.

**Comment by zukoj** [comment]
Proposed a fix for it
