### ISSUE TITLE
Using python2, but getting: : Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by grayaii** [rubik/radon#119]
When I run:
```
radon cc .
```
I get this error:

```
foo/foo.py
    ERROR: Missing parentheses in call to 'print' (<unknown>, line 65)
```

```
$ python --version
Python 2.7.10
$ radon --version
1.5.0
```

It seems to think it wants python3 syntax, despite I'm using python 2.

**Comment by rubik** [comment]
Radon uses the Python AST parser, therefore if it reports that error it means that it's using Python 3's AST module.

Can you try the following and report back?
```
$ virtualenv py2 -p python2
$ virtualenv py3 -p python3
$ echo "print 'foo'" > foo.py
$ source py2/bin/activate
$ pip install radon==1.5.0
$ radon cc foo.py
$ source py3/bin/activate
$ pip install radon==1.5.0
$ radon cc foo.py
```

By trying the above, I get the error only in the second case, as expected.

**Comment by grayaii** [comment]
dang! I'm getting the same results as you now.  I will check my env a bit more carefully to see if i can reproduce the problem.  Sorry to have wasted your time.
