### ISSUE TITLE
mando requirements very heavy + mismatched requirements.txt and setup.py

### ISSUE THREAD

**Issue by Deimos** [rubik/radon#120]
The minor thing first: setup.py has `'mando>=0.5,<0.6'` while requirements.txt has `mando>=0.3,<0.4`.

I noticed this because the upgrade to radon 2.0.0 (which upgraded mando to 0.5) installed a huge number of new packages as well:

```
  - mando
    - sphinx
      - alabaster
      - babel
        - pytz
      - docutils
      - imagesize
      - Jinja2
        - MarkupSafe
      - Pygments
      - requests
        - certifi
        - chardet
        - idna
        - urllib3
      - setuptools
      - six
      - snowballstemmer
      - sphinxcontrib-websupport
```

Maybe this should be an issue on the mando project instead, but is installing sphinx really necessary for mando? That's *way* more packages than I want to add to my project just to support Radon, so at least for me it's probably going to result in me no longer using Radon.

**Comment by rubik** [comment]
Hi Chad,
thanks for the report.

Indeed, the requirements.txt file is out-of-date. The other issue should be on the mando project, but we can avoid the hassle of moving the issue since I'm the maintainer of both projects.
First of all, let me say that I agree with you that having that many dependencies for mando is too much. And the majority of them aren't even used! The Sphinx dependency is only there to supply the `sphinx.ext.napoleon` package, which allows mando to support Sphinx-,Numpy-, or Google-style docstrings. It was once a separate package but it got merged into Sphinx.

Possible solutions include making the Sphinx dependency optional or making `napoleon` a vendored dependency to be shipped with mando. I'm leaning towards the latter, as that package is the only one that's really needed and it's not updated very often in Sphinx anyway.

**Comment by Deimos** [comment]
Thanks for the quick response, and I'm glad you're interested in trying to reduce the dependencies. I was definitely surprised when I saw how many new things showed up after upgrading yesterday.

I think both of your suggested options sound like good approaches, so whichever one works out the simplest is probably great.

**Comment by rubik** [comment]
So, I have reduced mando dependencies. I have released version v2.0.2 which has the correct dependency requirements.

It appears that now we have another problem, much like this one: `flake8-polyfill` depends on `flake8`, which in turns brings in a number of unneeded dependencies. Namely:
```
- pycodestyle
- pyflakes
- mccabe
```

This `flake8` dependency is really only needed for its version!
https://github.com/PyCQA/flake8-polyfill/blob/master/src/flake8_polyfill/version.py#L3

If we want to reduce dependencies even further, to require only what we actually use, we should contact `flake8_polyfill` maintainers.

**Comment by kfir-rocketrip** [comment]
Unfortunately it looks like v2.0.2 is broken when it comes to dependencies.  This is the error I got on a fresh install.

`  0 Traceback (most recent call last):
  1   File "/Users/xyz/.pyenv/versions/rocketrip.venv/bin/radon", line 11, in <module>
  2   sys.exit(main())
  3   File "/Users/xyz/.pyenv/versions/3.5.2/envs/rocketrip.venv/lib/python3.5/site-packages/radon/__init__.py", line 10, in main
  4   from radon.cli import program, log_error
  5   File "/Users/xyz/.pyenv/versions/3.5.2/envs/rocketrip.venv/lib/python3.5/site-packages/radon/cli/__init__.py", line 5, in <module>
  6   from mando import Program
  7   File "/Users/xyz/.pyenv/versions/3.5.2/envs/rocketrip.venv/lib/python3.5/site-packages/mando/__init__.py", line 8, in <module>                                                     raise e
  8   File "/Users/xyz/.pyenv/versions/3.5.2/envs/rocketrip.venv/lib/python3.5/site-packages/mando/__init__.py", line 4, in <module>                                                     from mando.core import Program
  9   File "/Users/xyz/.pyenv/versions/3.5.2/envs/rocketrip.venv/lib/python3.5/site-packages/mando/core.py", line 17, in <module>                                                        from mando.napoleon import Config, GoogleDocstring, NumpyDocstring
 10   ImportError: No module named 'mando.napoleon' `

**Comment by kingink** [comment]
Unfortunately it looks like v2.0.2 might be broken when it comes to dependencies.  This is the error I got on a fresh install.

`  0 Traceback (most recent call last):
  1   File "/Users/xyz/.pyenv/versions/rocketrip.venv/bin/radon", line 11, in <module>
  2   sys.exit(main())
  3   File "/Users/xyz/.pyenv/versions/3.5.2/envs/rocketrip.venv/lib/python3.5/site-packages/radon/__init__.py", line 10, in main
  4   from radon.cli import program, log_error
  5   File "/Users/xyz/.pyenv/versions/3.5.2/envs/rocketrip.venv/lib/python3.5/site-packages/radon/cli/__init__.py", line 5, in <module>
  6   from mando import Program
  7   File "/Users/xyz/.pyenv/versions/3.5.2/envs/rocketrip.venv/lib/python3.5/site-packages/mando/__init__.py", line 8, in <module>                                                     raise e
  8   File "/Users/xyz/.pyenv/versions/3.5.2/envs/rocketrip.venv/lib/python3.5/site-packages/mando/__init__.py", line 4, in <module>                                                     from mando.core import Program
  9   File "/Users/xyz/.pyenv/versions/3.5.2/envs/rocketrip.venv/lib/python3.5/site-packages/mando/core.py", line 17, in <module>                                                        from mando.napoleon import Config, GoogleDocstring, NumpyDocstring
 10   ImportError: No module named 'mando.napoleon' `

**Comment by rubik** [comment]
Weird. I tested it in a fresh virtualenv! Let me take a look.

**Comment by rubik** [comment]
Indeed, it was a problem with mando and the new changes, my bad. I pushed a new version (v0.6.4) and tried it thoroughly in a new env.

**Comment by Deimos** [comment]
It looks great to me, thanks very much for addressing that so quickly, @rubik . I upgraded radon from 1.5.0 to 2.0.2 and this time the only other change was mando going from 0.3.3 to 0.6.4 with no other new packages added.
