### ISSUE TITLE
Errors with code R701 aren't included into pepper8 report

### ISSUE THREAD

**Issue by aleskarovadi** [rubik/radon#121]
Hi! I would like to use radon with flake8 to check my code and then to transform flake8 output into html report using pepper8 tool. But errors found by radon plugin for flake8 aren't included into this report.

Example:
I run flake8 with the command ```flake8 --output output/report.txt --radon-max-cc 5 linter/``` and get several error messages in ```report.txt```:
```
linter/rules/testrail_rule.py:7:1: R701: 'TestRailTagLinkCheck' is too complex (6)
linter/rules/testrail_rule.py:16:80: E501 line too long (107 > 79 characters)
```

When I want to generate html report with command ```pepper8 -o output/report.html output/report.txt```, there is only the second error message in report.html

I think this is because radon error message put ```:``` after error code ```R701:``` and pepper8 doesn't recognize it as valid (it check if error code matches this regEx ```ERROR_CODE = re.compile('^[a-zA-Z][0-9]{3,4}$')``` while generating the report). When I remove ```:``` from error message (```linter/rules/testrail_rule.py:7:1: R701 'TestRailTagLinkCheck' is too complex (6)```), it get into pepper8 report.

Is it possible to change error_tmpl by removing ```:``` after error code so the error messages will be included into pepper8 report?

**Comment by rubik** [comment]
Thanks for the very detailed issue.
I actually don't ever recall reading a specification about this, so I don't think there's any problem altering the message.
