### ISSUE TITLE
Radon 2.0.0 does not work correctly with async/await

### ISSUE THREAD

**Issue by maqquettex** [rubik/radon#122]
![image](https://cloud.githubusercontent.com/assets/17751432/26800445/ffdfa65a-4a41-11e7-8846-4570f01187cf.png)

After trying to check CC of my aiohttp-based project I discovered radon does not work with async/await syntax. Files without async/await syntax are parsed and checked fine.

python version: 3.6.1
radon: 2.0.0 (installed with pip install radon==2.0.0)

According to #90 I tried to use radon v1.4.0 and 1.5.0, both of them failed too.
It could be error of python versions, but I cannot check it right now.

Looking forward to reply

**Comment by rubik** [comment]
I just tested your file and radon parses it correctly. As said elsewhere, SyntaxError's are not possible, since radon uses the AST parser bundled with Python. Therefore, if Python can parse the file, radon can analyze it.

You've probably installed radon with the Python 2 Pip.

**Comment by maqquettex** [comment]
Looks like you`re right, somehow radon executed from python2. Tested with virtualenv and python3, works like a charm.
Thanks for quick reply, i`m closing issue due to the absence of a crime :)
