### ISSUE TITLE
should the with statement add to cyclomatic complexity?

### ISSUE THREAD

**Issue by gdub** [rubik/radon#123]
The docs state that the `with` statement adds to cyclomatic complexity because a `with` roughly corresponds to a `try`/`except`.

While a `with` statement does translate to a `try`/`except`/`finally` under the hood, why should this count towards the complexity of the code containing the `with` statement?  There is no additional execution branch present in the code containing the `with` statement, is there?  That complexity (i.e. additional execution branch) is factored out to the code that defines the context manager utilized by the `with` statement.

For example, say I define a context manager:
```python
@contextmanager
def transaction(db):
    db.begin()
    try:
        yield None
    except:
        db.rollback()
        raise
    else:
        db.commit()
```
...and utilize this in a function:
```python
def write_to _db(db):
    with transaction(db):
        db.insert(...)
```
The `transaction` context manager function is going to have a complexity based on the code paths introduced by the `try`/`except`/`else`, but I wouldn't think you would want to double-count that complexity for the `with` statement used within the `write_to_db` function.

**Comment by rubik** [comment]
I agree and I have finally implemented this. I apologize for the long delay.
