### ISSUE TITLE
Add a command for the halstead complexity

### ISSUE THREAD

**Issue by AsnelChristian** [rubik/radon#125]
Maybe there should be a command that returns the measure of the halstead complexity.

**Comment by rubik** [comment]
I had thought about it initially, but it would be a lot of work for something of dubious utility. I regret adding the `mi` command for the same reason. The important ones are `cc` and `raw`. If someone wants to take a shot at it, I'll happily review the changes. It has to follow the `Harvester` API like the other commands.
