### ISSUE TITLE
Docker container does start ONLY and nothing happens

### ISSUE THREAD

**Issue by Spirit328** [rubik/radon#132]
Hi rubik!

Let me start with a huge "THANK YOU" for radon.
As I am not good in Python things, I went to the Docker container solution.

I did a docker build -t radon . (in the directory where the Dockerfile is) and Docker built the container without complains.

But then it just starts, says
~~~~
$ docker run -it radon:latest
Running radon3...
~~~~
... and dies.

I think this is because of the parameters given after CMD in the Dockerfile, right?
How could I make it check my source-code directories in /home/<user>/<project>/source

Would it be possible to provide the parameters to the docker container as variables?

Thank you very much in advance for your answer

Cheers
Thorsten

**Comment by rubik** [comment]
Hi Thorsten,
thank you for your kind words.

The Docker setup is there for CodeClimate. You can either enable radon from their web interface (if you use it) or you can host it yourself. You have to start from their README [here](https://github.com/codeclimate/codeclimate).

That said, if you want to analyze your local directories the above setup is really complicated in my opinion. It's much better to setup a Virtualenv (which you can use for other Python packages) and install radon inside it. If you don't have one, check out [this guide](http://docs.python-guide.org/en/latest/dev/virtualenvs/).

Once you have a virtual environment in place, it's very easy to install and use radon. As with any other Python package, you activate the environment and then install it via Pip: `pip install radon`. Then you can call radon like any other programs: `radon cc /home/source [...]`.

**Comment by Spirit328** [comment]
Sorry for not replying earlier.

I quit using a container (for this case).
THANK YOU very much for your fast answer. It helped me very much.

Cheers
Thorsten
