### ISSUE TITLE
radon fails to read files with utf-8 with BOM encoding on Windows

### ISSUE THREAD

**Issue by SowingSadness** [rubik/radon#139]
![image](https://user-images.githubusercontent.com/576443/38365929-cbeef992-38e6-11e8-9a0f-69404555d250.png)

[utf8-bom.zip](https://github.com/rubik/radon/files/1879986/utf8-bom.zip)

**Comment by rubik** [comment]
Hi, at the moment I'm very busy and I don't have time to debug this unfortunately. However, I've already received similar reports in the past and in all cases it was either a Python 2 problem or the person who reported the problem couldn't reproduce it consistently. If you find a problem and open a PR I will gladly review it.

**Comment by SowingSadness** [comment]
@rubik Thanks for you'r answer! I was on of that persons :)
The problem was about a file encoding in past. 
This is another issue. I used radon 2.2.0 and Python 3.3.5. It is about BOM symbols only.
Radon + Python 3 + Windows + utf-8 without BOM work correct.
I will try to create PR if i can.

**Comment by rubik** [comment]
@SowingSadness Ha! If you can manage a PR I would be very grateful.

**Comment by rubik** [comment]
I see that the PR on xbmc/repo-plugins got merged. I assume I can close this issue. Feel free to reopen.
