### ISSUE TITLE
using radon programmatically

### ISSUE THREAD

**Issue by mzfr** [rubik/radon#141]
Is it possible to use the `radon.raw.analyze` function with the directory path ?

What I want is the average of all the lloc, loc etc. 
In CLI we do: `radon raw <dir_path> -s` this give all the metrics and then in the end it gives the `** TOTAL **` I want to get that total thing but with code.

**Comment by rubik** [comment]
Yes, it's possible. Look at how Xenon does it:
https://github.com/rubik/xenon/blob/e48b1394482d5bafa6e2dc0cd983845b1093aa00/xenon/core.py#L10-L34

You have to create a `Config` object and a `Harvester` object and then you can call the analyze method.
