### ISSUE TITLE
--exclude doesn't exclude explicit filenames

### ISSUE THREAD

**Issue by rwbogl** [rubik/radon#149]
If a filename is explicitly given at the command line, then the `-e` and `--exclude` flags will not exclude these files. For example, `radon cc --exclude test.py test.py` will still visit `test.py`. This might be expected behavior, but it's in conflict with the documentation for `-e`: "Exclude files only when their path matches one these glob patterns."

The culprit is [this line](https://github.com/rubik/radon/blob/e3c1e1cab50765fc0fbcf559b787abf06a03b41a/radon/cli/tools.py#L216), which passes explicit filenames through.

**Comment by rubik** [comment]
Thanks for pointing out this inconsistency between the documentation and the actual behavior. Honestly I don't know what is best in this case. Probably `exclude` should take the precedence. What do you think?

**Comment by rwbogl** [comment]
I think that you're right; `exclude` should take precedent over any explicit files. I haven't used this feature yet, so I don't know if there's a good reason to do anything else.

Do you know any other sensible option?

**Comment by rubik** [comment]
@rwbogl I'll release this fix in version 2.3.1
