### ISSUE TITLE
Since 2.3.1, radon produces no output to the console

### ISSUE THREAD

**Issue by hawkeyej** [rubik/radon#155]
Radon 2.3.0 works fine with python 3.7.0 and 3.6.6

Starting with 2.3.1, no output to the console

Linux Mint 17.3

**Comment by rubik** [comment]
I cannot reproduce this. For me it works fine. What terminal are you using? Can you also provide a sample file?

**Comment by hawkeyej** [comment]
It looks like the problem is that it now ignores files without a .py extension.

Many of my python files to not have a .py extension (command line utilities).

**Comment by hawkeyej** [comment]
Can you please fix this?
Trust the user to pass python files even if there is no .py extension.

**Comment by rheber** [comment]
The problem is iter_filenames() in tools.py. The pattern '*[!p][!y]' is always added to the exclude list, even if the user passes in a custom list of exclude patterns.

It's not obvious to me what the correct solution would be. Possible solutions:

* Don't use the default pattern if the user specifies a custom list of exclude patterns

* Add a flag that removes the default pattern from the list of exclude patterns

**Comment by hawkeyej** [comment]
The solution is simple. Allow the user to specify files on the command line (that is what it does now) and respect that list of files (that is NOT what it's doing now).

**Comment by hawkeyej** [comment]
This is how I patched my local copy of radon/cli/tools.py
```
def _is_python_file(filename):
    """Check if the file is python."""
    if filename.endswith('.py'):
        return True
    with open(filename, 'r') as myfile:
        line = myfile.readline()
        if line.startswith('#!') and ('python' in line):
            return True
    return False


def iter_filenames(paths, exclude=None, ignore=None):
    '''A generator that yields all sub-paths of the ones specified in
    `paths`. Optional `exclude` filters can be passed as a comma-separated
    string of regexes, while `ignore` filters are a comma-separated list of
    directory names to ignore. Ignore patterns are can be plain names or glob
    patterns. If paths contains only a single hyphen, stdin is implied,
    returned as is.
    '''
    if set(paths) == set(('-',)):
        yield '-'
        return
    e = ''
    exclude = '{0},{1}'.format(e, exclude).split(',') if exclude else [e]
    ignore = '.*,{0}'.format(ignore).split(',') if ignore else ['.*']
    for path in paths:
        if (os.path.isfile(path) and _is_python_file(path) and
                (not exclude or not any(fnmatch.fnmatch(path, p)
                                        for p in exclude))):
            yield path
            continue
        for filename in explore_directories(path, exclude, ignore):
            yield filename


def explore_directories(start, exclude, ignore):
    '''Explore files and directories under `start`. `explore` and `ignore`
    arguments are the same as in :func:`iter_filenames`.
    '''
    for root, dirs, files in os.walk(start):
        dirs[:] = list(filter_out(dirs, ignore))
        fullpaths = (os.path.normpath(os.path.join(root, p)) for p in files)
        for filename in filter_out(fullpaths, exclude):
            if (not os.path.basename(filename).startswith('.') and
                    _is_python_file(filename)):
                yield filename

**Comment by rubik** [comment]
@hawkeyej @rheber This issue has been fixed, I'll push a new version shortly. I apologize for the long delay.

**Comment by hawkeyej** [comment]
@rubik Thanks
