### ISSUE TITLE
How does Radon cc calculate a class's complexity?

### ISSUE THREAD

**Issue by DungxNguyen** [rubik/radon#156]
I can not find any documentation about how Radon cc calculates a class's complexity, then I assume from its outputs that it average a class's methods' complexities and round it to the nearest integer.

Then I test Radon with this class. It has 6 methods, 5 with complexity of 1 and the other with complexity of 5. THen the average is 1.66 and Radon should report 2. In fact, it returns 1.

If I add 1 more IF statement to it, then the complexity is raised to 2 (average is 1.8). 

I attach here the test file.

Best,
[large_class.py.txt](https://github.com/rubik/radon/files/2491955/large_class.py.txt)

**Comment by rubik** [comment]
A class' complexity is calculated here:
https://github.com/rubik/radon/blob/master/radon/visitors.py#L78

We currently do not round towards the nearest integer, but rather apply the floor operator. We add 1 to the result if the class has methods. Maybe you are onto something here and we should round.

**Comment by DungxNguyen** [comment]
So it's the output from Radon
    M 2:2 A.f1 - A (5)
    C 1:0 A - A (1)
    M 12:2 A.f2 - A (1)
    M 15:2 A.f3 - A (1)
    M 18:2 A.f4 - A (1)
    M 21:2 A.f5 - A (1)
    M 24:2 A.f6 - A (1)

**Comment by DungxNguyen** [comment]
> A class' complexity is calculated here:
> https://github.com/rubik/radon/blob/master/radon/visitors.py#L78
> 
> We currently do not round towards the nearest integer, but rather apply the floor operator. We add 1 to the result if the class has methods. Maybe you are onto something here and we should round.

So the results should be [ (5+1 x 5) / 6 ] + 1 = 2, but Radon still reports 1?

**Comment by rubik** [comment]
@DungxNguyen I apologize for the delay. You were correct, except that you also have to add the 1 in complexity from which all classes/functions start with. So the correct calculation is:

[(1 + 5 + 1 x 5) / 6] + 1 = 2

I have fixed it and I'll release a new version shortly.
