### ISSUE TITLE
Support Python 3.7

### ISSUE THREAD

**Issue by DonJayamanne** [rubik/radon#159]
Does this officially support Python 3.7.
The docs seem to state that 3.6 is the latest Python version supported.
& thanks for this great package, I've used this a lot.

**Comment by rubik** [comment]
I am using it myself on Python 3.7 and it seems to work fine. Unfortunately Travis does not support Python 3.7 yet, so I haven't updated the docs.

**Comment by rubik** [comment]
Both the documentation and the README now state the support for Python 3.7, and Travis supports it as well.
