### ISSUE TITLE
colorama dependency version conflict with pytest

### ISSUE THREAD

**Issue by flazzarini** [rubik/radon#164]
Hi there when I am installing `radon` onto a virtual environment which has already pytest installed I get the following error message

```
radon 2.4.0 has requirement colorama<0.4,>=0.3, but you'll have colorama 0.4.1 which is incompatible.
```

pytest somehow has no restriction of colorama so it installs (at the time of writing) `v0.4.1`. Would it be possible that you upgrade the version of colorama in your package?

Thanks for your help!

**Comment by rubik** [comment]
I have updated the requirements, thanks for the heads up. I'll release a new version shortly.
