### ISSUE TITLE
UTF-8 codec error caused during reading binary files in Radon 3.0.0

### ISSUE THREAD

**Issue by tisnik** [rubik/radon#166]
It seems like Radon 3.0.0 tries to open and analyze _all_ files (not only Python sources) when started by:

```
radon cc -s -a -i venv .
```

But when there exist any binary files(or text file not stored with UTF-8 encoding), it stops with the following error message:

```
ERROR: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
```

Radon 2.4.0 seems to behave correctly.

**Comment by rubik** [comment]
@tisnik @CalebSchwarz @cverna @pypingou @bemcculley @moochannel @scolby33 Fixed in 3.0.1 which was uploaded to PyPI. Thanks for the heads up.
