### ISSUE TITLE
Fails to Execute if File Contains Unicode

### ISSUE THREAD

**Issue by DevynCJohnson** [rubik/radon#169]
If I have Radon scan a file that contains a Unicode character (or any character outside of the ASCII range), Radon throws the error message `ERROR: 'ascii' codec can't decode byte 0xc2 in position 7628: ordinal not in range(128)`. Obviously, if I check that location in my script, that character is not part of the ASCII range. I am using the newest version of Radon from the PyPi repository (v3.0.1). I am using Python3.6 and I have tried Python3.7.

**Comment by rubik** [comment]
Sorry for the late reply. The encoding that Radon selects to read the file is the one returned by `locale.getpreferredencoding(False)`. You can override it by setting the environment variable `RADONFILESENCODING`. Let me know if this solves the issue.

**Comment by DevynCJohnson** [comment]
Setting that environment variable did the trick. Thanks!
