### ISSUE TITLE
MathJax Error in Docs

### ISSUE THREAD

**Issue by rmorshea** [rubik/radon#177]
# Screenshot

![image](https://user-images.githubusercontent.com/4041990/63049549-ccf84680-be8d-11e9-9cd1-c0062e4c5946.png)

# Logs

![image](https://user-images.githubusercontent.com/4041990/63049768-4ee86f80-be8e-11e9-813c-f4724ecef9df.png)

**Comment by rubik** [comment]
I cannot reproduce this issue, for me it loads fine. Can you try from an incognito session'

**Comment by rmorshea** [comment]
Welp, not sure what was wrong. I'm not able to reproduce either.
