### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by tonybaloney** [rubik/radon#178]
I've been using radon extensively in my own project [wily](https://github.com/tonybaloney/wily) and just wanted to say thanks for writing such an awesome library.

I would really like to contribute to this package, but it's worked so seamlessly, I've never had any issues!

💯

**Comment by rubik** [comment]
Thank you!

It's great that it's been useful to many people, I'm very happy about that. Currently I don't have much time myself to work on radon, but there are a few issues that have been open for long. The most important one would be allow the user to specify the options in `setup.cfg` where many other tools are already storing theirs (e.g. Flake8, isort, etc.). This has been asked a few times already and it shouldn't be too difficult, if you want to take a crack at it.

**Comment by tonybaloney** [comment]
cool! that's a good idea. Theres a lot of options so I'll have a think through how that might work

**Comment by tonybaloney** [comment]
Link #179

**Comment by tonybaloney** [comment]
Closing as #179 is now merged.

**Comment by rubik** [comment]
@tonybaloney I have released version 4.0.0 with your changes. I also added your name to the changelog. Thanks again, those two features are extremely useful!

**Comment by tonybaloney** [comment]
Awesome! thank you
