### ISSUE TITLE
Feature Request: Force coloured output

### ISSUE THREAD

**Issue by reynoldscem** [rubik/radon#182]
When I pipe radon into something else (`less`) it disables coloured output. This is obviously reasonable default behaviour. But a flag for forcing coloured output would be great, for use with a pager that accepts colours.

**Comment by rubik** [comment]
It seems a useful feature. It's also probably easy to implement, but I think the soonest I can look at this is the next weekend. Otherwise, I'll happily review any PR.

**Comment by reynoldscem** [comment]
Thanks. I'm not very well at the moment so I'm unlikely to get a PR in anytime soon - but I'll @ you if I do. Thank you.
