### ISSUE TITLE
How to find cc for code not inside functions , method or classes

### ISSUE THREAD

**Issue by kush96** [rubik/radon#186]
Consider the piece of code below:
```
############
# piece of code for which Cyclo is not apparently calculated
x = 10
if x > 5 and x<10:
  pass
elif x == 7:
  pass
#############

def foo(x):
  if(True):
    pass

class OurClass:
  if(True):
    pass
```
I couldn't find cc either programatically or through cli for the first 5 lines of code, here's what showed up :
1. CLI
`radon cc -s  myPythonFile.py`
Result

```
> myPythonFile.py
>     F 7:0 foo - A (2)
>     C 11:0 OurClass - A (2)
> 
```

2. Python
```
>>> inputFile = '/Users/singhkus/Blueoptima/Repos/integrator/metrics.validation.input/myPythonFile.py'
>>> with open(inputFile) as f:
...   programString = f.read()
...   programCycloMetric  = cc_visit(programString)
>>> for obj in programCycloMetric:
...     print(obj)
```
Result
```
F 7:0->9 foo - 2
C 11:0->13 OurClass - 2

```

In both the cases cyclomatic complexity does not show up for the first 5 lines, is there anyway i can get out the cyclomatic complexity of the code in question?

**Comment by rubik** [comment]
Yes, lines outside a block are not counted. That's because it's considered bad practice to have a lot of code at the global level. The only way to analyze those is to extend [`radon.visitors.ComplexityVisitor`](https://github.com/rubik/radon/blob/master/radon/visitors.py#L122) manually.
