### ISSUE TITLE
Feature request: __doc__ strings to be counted as comments, not code

### ISSUE THREAD

**Issue by cleder** [rubik/radon#201]
I have a file where Maintainability Index is failing.
It does not have a lot of code, but it is extensively documented via `__doc__` strings

Removing the doc strings will improve the `mi` from B to A

Raw Metrics:
With doc strings:
```
    LOC: 984
    LLOC: 132
    SLOC: 128
    Comments: 0
    Single comments: 1
    Multi: 752
    Blank: 103
    - Comment Stats
        (C % L): 0%
        (C % S): 0%
        (C + M % L): 76%
```

without doc strings:
```
    LOC: 189
    LLOC: 120
    SLOC: 128
    Comments: 0
    Single comments: 1
    Multi: 0
    Blank: 60
    - Comment Stats
        (C % L): 0%
        (C % S): 0%
        (C + M % L): 0%
```

This is not the desired behaviour as the doc strings in python are a way of documentation.

**Comment by rubik** [comment]
Hi Christian, it's a good while I don't work on raw metrics, but as I remember docstrings should be counted as comments, indeed. Can you post a minimal example that reproduces this issue?

**Comment by cleder** [comment]
```
def add(a, b):
    """
    This is a demo to highlight the docstr vs comment metric.

    Bla Bla Bla
    Bla Bla Bla
    Bla Bla Bla
    Bla Bla Bla
    Bla Bla Bla
    Bla Bla Bla
    Bla Bla Bla
    Bla Bla Bla
    Bla Bla Bla
    Bla Bla Bla
    """
    return a + b
```
=>

```
 LOC: 16
    LLOC: 3
    SLOC: 2
    Comments: 0
    Single comments: 0
    Multi: 13
    Blank: 1
    - Comment Stats
        (C % L): 0%
        (C % S): 0%
        (C + M % L): 81%
```

vs.

```
def add(a, b):

    # This is a demo to highlight the docstr vs comment metric.

    # Bla Bla Bla
    # Bla Bla Bla
    # Bla Bla Bla
    # Bla Bla Bla
    # Bla Bla Bla
    # Bla Bla Bla
    # Bla Bla Bla
    # Bla Bla Bla
    # Bla Bla Bla
    # Bla Bla Bla

    return a + b
```
 => 

```
 LOC: 16
    LLOC: 2
    SLOC: 2
    Comments: 11
    Single comments: 11
    Multi: 0
    Blank: 3
    - Comment Stats
        (C % L): 69%
        (C % S): 550%
        (C + M % L): 69%
```
I am not concerned about the raw metrics as such but as #187 says the Halstead metrics are computed from this and I assume
the maintainability index as well.

**Comment by rharish101** [comment]
Hi, it seems like the raw metrics are working as documented. In your first example, the docstrings are counted as multi-line comments (as shown under `Multi:`). It's just that it's not reported as a comment, as specified in [the documentation](https://radon.readthedocs.io/en/latest/intro.html#raw-metrics):

> Comments: The number of comment lines. Multi-line strings are not counted as comment since, to the Python interpreter, they are just strings.

I think that instead of focusing on the raw metrics, we should focus on the MI code, which might be ignoring multi-line comments.

**Comment by rubik** [comment]
@cleder I can confirm what @rharish101 said. Docstrings are reported separately just because they are not really comments. However, commands like `mi` do count them as comments in their calculations.

**Comment by cleder** [comment]
8-) 
In #187 it was mentioned that the values reported in the raw metrics are used, I was misguided by that.
