### ISSUE TITLE
Change default file encoding to utf-8 for python3

### ISSUE THREAD

**Issue by mousetail** [rubik/radon#203]
According to [PEP 3120](https://www.python.org/dev/peps/pep-3120/), the default encoding for python source files is utf-8, not `locale.getpreferredencoding`. Since this module reads python files, it should follow the same convention.

You can specify the encoding manually with the `RADONFILESENCODING` environment variable, but it seems strange to have to jump through a hoop to get the standard python behavior.

**Comment by FredHappyface** [comment]
One workaround for this issue and other such 'misbehaving' programs is to add `-X utf8` to the py/python command. For example, in Windows:

```
py -X utf8 -m radon cc -s  . 
```

**Comment by rubik** [comment]
@mousetail @FredHappyface You are right, this was a bug. I made utf-8 the default encoding on Python 3.0+. I just released radon v4.4.0 with this change. Thanks!
