### ISSUE TITLE
Feature Request: parameter to specify configuration file path

### ISSUE THREAD

**Issue by cristianMeli** [rubik/radon#207]
Actually there is not a parameter to do this like in [flake8](https://flake8.pycqa.org/en/latest/user/options.html#cmdoption-flake8-config).
Testing, I think that radon only try to find a `radon.cfg` in the directory where radon is executed.
This feature will be great because the configuration file can be anywhere.

**Comment by rubik** [comment]
@cristianMeli Thanks Cristian, I just added this feature. You can specify a custom path with the `RADONCFG` environment variable. It's part of version 4.4.0 which I will release shortly.

**Comment by rubik** [comment]
Done, released radon v4.4.0.
