### ISSUE TITLE
Can't get the actual complexity for block of code

### ISSUE THREAD

**Issue by S3j5b0** [rubik/radon#216]
I have a project where I need to do some analysis of python applications.

I want to use the package 'Radon' in order to look at some python code (as a string) and get out a number indicating the complexity of the code.
In the documentation, there is this this example:

```
    >>> from radon.visitors import ComplexityVisitor
    >>> v = ComplexityVisitor.from_code('''
    def factorial(n):
        if n < 2: return 1
        return n * factorial(n - 1)
    
    def foo(bar):
        return sum(i for i in range(bar ** 2) if bar % i)
    ''')
    >>> v.functions
    [Function(name='factorial', lineno=2, col_offset=0, endline=4, is_method=False,
    classname=None, closures=[], complexity=2),
    Function(name='foo', lineno=6, col_offset=0, endline=7, is_method=False, classname=None,
    closures=[], complexity=3)] 
```

Ok, so this gives a list of these two functions and returns a bunch of metrics for both. I would like to just input some code, and get complexity of everything. This view is given by accessing `v.functions`, So im thinking I shouldd able to just call `v.complexity`:
```

    v = ComplexityVisitor.from_code('''
    def factorial(n):
        if n < 2: return 1
        return n * factorial(n - 1)
    
    def foo(bar):
        return sum(i for i in range(bar ** 2) if bar % i)
    ''')
    
    print(v.complexity)
```

But whenI run this, I get a complexity of 1? This is really weird, the complexity of the functions was 2 and 3 before, how can the accumulated complexity be 1 now?

It keeps being 1, no matter which code I put in. For example this code also has a complexity of 1:
```

    def complexcode(x):
          
        n = order(x)
        temp = x
        sum1 = 0
        tmp = [1,2,3,4,5,6,3,1,3,5]
        while (temp != 0):
            for i in tmp:
                if i == 10:def isArmstrong(x):
      
    n = order(x)
    temp = x
    sum1 = 0
    tmp = [1,2,3,4,5,6,3,1,3,5]
    while (temp != 0):
        for i in tmp:
            if i == 10:
                print
            print(i)
        r = temp % 10
        sum1 = sum1 + power(r, n)
        temp = temp // 10
  
    # If condition satisfies
    return (sum1 == x)
                    return
                print(i)
            r = temp % 10
            sum1 = sum1 + power(r, n)
            temp = temp // 10
      
        # If condition satisfies
        return (sum1 == x)

```
How do I get the complexity for an entire block of code?

EDIT: 
I now played around a bit more, and found out that the issue is that complexity for functions and driver code is calculated separetely. But the question pretty much remains. 
How do I get the complexity for all of the code? not individual functions and driver code separate?

**Comment by rubik** [comment]
@S3j5b0 For that you can use the high-level functions in the `radon.complexity` module: https://github.com/rubik/radon/blob/master/radon/complexity.py
