### ISSUE TITLE
Python 3.10: match-case syntax not yet supported by radon?

### ISSUE THREAD

**Issue by PedanticHacker** [rubik/radon#226]
I have analyzed cyclomatic complexity of a function that has this new Python 3.10 match-case syntax. The result of that function was `A (1)`. That's not correct. The function had a lot of case statements in it.

Is there any undergoing work yet to have radon analyze and correctly report cyclomatic complexity where there's match-case syntax in Python 3.10 code?

**Comment by DolajoCZ** [comment]
[Here](https://github.com/rubik/radon/pull/227) is PR for this issue.
