### ISSUE TITLE
5.1.0 - wrong import

### ISSUE THREAD

**Issue by hydrastarmaster** [rubik/radon#241]
In radon 5.1.0 there's the following error, which prevent the installation:
`from configparser import configparser, os`

Please change it with:
`from configparser import ConfigParser, os`

**Comment by rubik** [comment]
I don't see such import the code, please link the file within Radon that has it.

**Comment by hydrastarmaster** [comment]
The affected file was a test_cli.py. Now, the current 6.0.1 version is ok. The strange thing is that I installed the 5.1.0 on two different PCs with pip; one was ok, while the other had the problem I mentioned. Thus, the bug is not directly related to the packet maintenance, but some misalignment in the pip repo. I don’t think it deserves special attention, for the current version is ok and backward compatible. Just for curiosity, you could check which past version of the test_cli.py has the line with the double import (just to understand where pip got that thing). I close the issue for it's just as info.
