### ISSUE TITLE
HelloGitHub Badge

### ISSUE THREAD

**Issue by 521xueweihan** [rubik/radon#267]
<img width="782" alt="image" src="https://github.com/user-attachments/assets/84859672-d5cc-4e06-8877-db490df85b0d">

🎉 Congratulations! Your [project](https://hellogithub.com/en/repository/bbca7606a6b1412da1312d68ae81d781) has been featured and recommended by the HelloGitHub community. We invite you to join the HelloGitHub Badge Program. Joining will grant you the following privileges:

- **Community Recognition**: The badge indicates that your project has successfully passed the HelloGitHub community's stringent selection and recommendation process.
- **Increased Exposure**: Displaying the badge will draw more traffic to your project, attracting additional users and contributors.
- **Enhanced Interaction**: Users can quickly understand your project through the badge and engage with it (like, comment, bookmark).
- **Feedback Collection**: Gather genuine feedback from a broad user base, aiding in the continuous improvement of your project.
- **Special Identification**: Once verified, your comments will feature a distinctive mark and be prioritized for pinning.

📌 [Click here](https://hellogithub.com/en/repository/bbca7606a6b1412da1312d68ae81d781/embed) to wear the badge and join the HelloGitHub Badge Program, allowing your open-source project to shine even brighter.

**Comment by rubik** [comment]
Thanks @521xueweihan, I'm happy to be part of your initiative. I added the badge to the README.

**Comment by 521xueweihan** [comment]
@rubik Thank you for your support and claim. I have passed the claim review. If you encounter any problems, please contact me.
<img width="785" alt="image" src="https://github.com/user-attachments/assets/d76e9c12-f24f-4d61-8c0c-24eafa3c19a7">
