### ISSUE TITLE
Radon doesn't work with utf-8 encoded files

### ISSUE THREAD

**Issue by andredias** [rubik/radon#72]
```bash
$ radon --version
1.1.1
$ echo 'print("Olá Açúcar Lâmpada")' > /tmp/test.py
$ radon cc /tmp/test.py
/tmp/test.py
    ERROR: 'ascii' codec can't decode byte 0xc3 in position 9: ordinal not in range(128)
```

**Comment by rubik** [comment]
Unfortunately I cannot reproduce this bug. I tried with both Python 3.4 and 2.7. In both cases the command exits without errors.
Can you provide more information?

**Comment by jackmurphy** [comment]
When I followed @andredias steps my terminal stripped out the utf characters and radon passed. 

Maybe this will work better:
```
wget http://pastebin.com/raw.php?i=VTBrPu1M -O /tmp/not-ascii.py
radon cc /tmp/not-ascii.py
```

I'm running it in Ubuntu 14.04.1 LTS, python 3.4.0

**Comment by rubik** [comment]
@jackmurphy When I execute that code, I get (on Python 3.4):
```shell

$ radon cc /tmp/not-ascii.py
/tmp/not-ascii.py
    ERROR: invalid syntax (<unknown>, line 1)
```

**Comment by jackmurphy** [comment]
I get:
```
$ radon cc /tmp/not-ascii.py
/tmp/not-ascii.py
    ERROR: 'ascii' codec can't decode byte 0xc3 in position 2: ordinal not in range(128)
$ radon --version
1.2
```

**Comment by rubik** [comment]
Damn, I tried with Python 2, and really cannot reproduce it. You suggested it may be the terminal: I'm running URxvt, or rxvt-unicode. What is yours?

**Comment by andredias** [comment]
I can't reproduce the very defect I reported anymore. Maybe because I've changed some locale settings.

**Comment by rubik** [comment]
Damn, this is getting difficult. Let's hope @jackmurphy will be able to shed some insight on this.

**Comment by lsh-0** [comment]
was nobody able to replicate this? I'm getting it now:

`WARNING:xenon:cannot parse src/publisher/tests/test_ajson_ingest.py: 'ascii' codec can't decode byte 0xc4 in position 23933: ordinal not in range(128)`

I'll try and reduce this down to something repeatable.
