### ISSUE TITLE
Radon doesn't report line numbers in XML output

### ISSUE THREAD

**Issue by tiyberius** [rubik/radon#75]
Radon currently reports the `complexity`, `unit`, `classification` and `file` for a given metric. A snippet of an XML report might look like:

```xml
<metric>
    <complexity>4</complexity>
    <unit>Services.enabled_services</unit>
    <classification>A</classification>
    <file>providers/services.py</file>
</metric>
```

I understand that Radon wasn't built to produce XML to be consumed by the [Jenkins CCM plugin](https://wiki.jenkins-ci.org/display/JENKINS/CCM+Plugin), but it would be nice if line numbers could be included in the metric because the CCM plugin looks for `startLineNumber` and `endLineNumber` to generate links for the report so that you can go straight to the code that the metric is referencing.

**Comment by rubik** [comment]
Fair enough, it's an easy addition and I think it's handy to have it around.

**Comment by rubik** [comment]
Let me know if it works as intended!

**Comment by tiyberius** [comment]
Awesome! When you have something that you think works, let me know and I will gladly test it in my environment

**Comment by tiyberius** [comment]
It works!!! This is awesome. You rock.

**Comment by rubik** [comment]
Nice! :cake:
