### ISSUE TITLE
coala

### ISSUE THREAD

**Issue by sils1297** [rubik/radon#80]
Hi,

I just wanted to tell you that since a short time, radon is available in coala which means people can use it from various editors, in your CI or even to review github PRs automatically, a HTML report is in the making. (The goal of coala is to provide usability to arbitrary static code analyhsis, prevent everyone from rewriting his own UI.)

With that you get everything you need also for CI (https://github.com/rubik/radon#on-a-continuous-integration-server) as you can configure radon via coala to e.g. only yield issues if there's something D or worse which will result in a neat output and a nonzero exitcode.

We're happy to receive any feedback/opinions if you have any of that. If you just want to ignore us feel free to close this report, otherwise maybe the projects can profit from each other in some way :)

**Comment by sils1297** [comment]
fwiw radon is only available in the development release i.e. `pip3 install coala --pre`

**Comment by rubik** [comment]
That's great! I'll try it and then I'll add a link on the README.
I was looking at the code, and was wondering: why `radon_ranks_info` in `RadonBear` is empty? I would expect it to be `('A', 'B')`. I'm talking about this piece of code:
https://github.com/coala-analyzer/coala/blob/master/bears/python/RadonBear.py#L14

I have not yet read about how bears work, so I apologize if it's a feature and I don't know it.
Thanks for letting me know! :+1:

**Comment by sils1297** [comment]
the info results are shown by default and we don't want to bother the user with non problematic code.

If you want, drop by for a chat at https://gitter.im/coala-analyzer/coala :)

**Comment by sils1297** [comment]
Though from the sound of "info" we might want to change the default simply since that is indeed an information...
