### ISSUE TITLE
is_multiline_string fails if previous_line length is less than 3

### ISSUE THREAD

**Issue by mrkeir** [rubik/radon#81]
The check '=' in previous_line[-3] within is_multiline_string (raw.py) fails with an ERROR: string index out of range if the previous line is less than 3 characters.

e.g:

    def function(
        args
    ):
        """This is a multi-line docstring
        for the function
        """
        pass

You will get string index out of range using `radon mi <filename>`  with the code above saved in <filename>

One fix would be:

    --- raw.py	2016-03-01 14:50:34.000000000 +0000
    +++ raw_fix.py	2016-03-01 14:50:44.000000000 +0000
    @@ -173,7 +173,7 @@
         line = doc[line_count]
         previous_line = doc[line_count - 1]
         if line.count('=') > 0 and line.index('=') < line.index(quote_type)\
    -            or line_count != 0 and '=' in previous_line[-3]:
    +            or line_count != 0 and len(previous_line) > 2 and '=' in previous_line[-3]:
             return True
    
         else:

**Comment by rubik** [comment]
Ouch! Thanks for the report!
