### ISSUE TITLE
Fixing versions of required libs

### ISSUE THREAD

**Issue by sils1297** [rubik/radon#82]
Hey! It's us again from coala.

Seems you just did a release with this line:
https://github.com/rubik/radon/blob/master/setup.py#L21

And it's giving us a lot of headaches (and CI failures) because you fix the colorama version to 0.3.6. So we have had long discussions last night and first off we don't know what's the best way to handle dependencies.

We totally see that it's a huge value to fix the dependencies to a certain version as your stability increases, you can rely on your program to not have any issues due to any new releases of your dependency. OTOH if you have users that possibly want to use coala/radon on their python application you don't want to require them to

a) Fix their requirements to yours if they overlap or
b) Make an own virtualenv just for code checking.

In general you'd rather want your requirements a bit more flexible because otherwise the user will be spending half of his workday working around clashing dependencies.

What is your stand on that discussion?

**Comment by rubik** [comment]
I read the discussion on coala-analyzer/coala#1852. I agree that fixing versions and forcing the user to use a different virtualenv is not doable. I'd prefer to use `>=` but still disallow a major version increment.

The downside of this approach is that we would then have to update our requirements in sync, everytime a major version of a dependency is released. As for assessing how big of a hassle this will be, we need to list all the dependency and see how often they release a major version. For the two dependencies that radon has, I know that they have never had a major version update:
* colorama is still at `0.3.7`
* mando is at `0.3.3` and I'm the author and maintainer of it.

**Comment by sils1297** [comment]
Well with those specific dependencies there's the problem that a minor increase can actually break the API since they haven't reached 1.x yet so if you want the dep to be API stable and it's in the 0.x stage you don't want to allow a minor version increment even.

**Comment by rubik** [comment]
You are right, but consider that colorama has been very stable from the start. I've been using it for years and it never broke. Of course, since it's not 1.x yet it can break at any time, but I deem it unlikely considering its history.

**Comment by sils1297** [comment]
might make sense for them to release a 1.0 then IMO. So a good policy would be to use `package>=0.2,<0.3` or `package>=1.x,<2.0` for requirements I guess

**Comment by rubik** [comment]
Yeah, I agree that the rules you propose would be best. I'll be releasing a new version with the fixed requirements shortly.

**Comment by sils1297** [comment]
Apparently there is https://www.python.org/dev/peps/pep-0440/#compatible-release and using `~=` sounds like the thing to do.

**Comment by rubik** [comment]
Wow, that's exactly what is needed here. I didn't even know about the compatible release operator.

**Comment by sils1297** [comment]
hey, this is really hurting us, you'd help us by far if you could do a micro release just replacing your `==` for colorama with `~=` like ASAP, tomorrow is FOSSASIA and we want lots of people to try out our new shiny software there. This is still affecting them...

**Comment by rubik** [comment]
I'm sorry, I made the changes locally and then tested a couple of things but didn't commit.

**Comment by rubik** [comment]
Done. Radon 1.3.1 is on PyPI.

**Comment by sils1297** [comment]
thank you so much! You've made my day :)
