### ISSUE TITLE
Support configuration file

### ISSUE THREAD

**Issue by caiofbpa** [rubik/radon#85]
I use radon on CodeClimate, and it's the only engine that requires configuration inside my `.codeclimate.yml` file. It would be much more straightforward to have a `.radon.yml` or `.radon.txt` file with the configurations, so I could run `codeclimate analyze -r radon` and/or `radon` itself and have the same output without having to figure which parameters codeclimate passes for each configuration on `.codeclimate.yml`.

**Comment by rubik** [comment]
That's a reasonable point, but unfortunately Radon follows CodeClimate's Engine specification, which you can find here:
https://github.com/codeclimate/spec/blob/master/SPEC.md

The spec states that all the configuration (for all engines) happens in `.codeclimate.yml`. You could propose a change to the spec.

**Comment by caiofbpa** [comment]
Thanks for your quick response @rubik!

Take look at CodeClimates's [pep8 engine docs](https://docs.codeclimate.com/docs/pep8). You can configure CodeClimate-related stuff on `.codeclimate.yml` (like which files will get rated), but pep8 configuration should happen on the `.pep8` file.

Do you see that as a spec violation?

**Comment by rubik** [comment]
I wouldn't say it's a spec violation, as the spec isn't really precise on this topic.
If I understand correctly, you want to be able to specify radon config in its own file? And the `.codeclimate.yml` would then be used only to decide which files to analyze?

**Comment by caiofbpa** [comment]
I would like even the decision about which files to analyze (or ignore) to be in radon's own config file.

But if you agree to add only the threshold configs, that would still be an improvement to me.

**Comment by mrb** [comment]
@caiofbpa @rubik Hi! Sorry I missed this issue. It's totally okay spec-wise to have a config file outside of the .codeclimate.yml. Engines will typically search for the standard config file (e.g. Rubocop looks for `.rubocop.yml`) and Radon could behave the same way.

**Comment by caiofbpa** [comment]
Any developments regarding this? I'm not using radon anymore, so I'm favorable to closing this issue if this isn't relevant to anyone else anymore.

**Comment by rubik** [comment]
@caiofbpa You can leave it open as it is definitely something useful that would improve Radon's usability. Presently I don't have time to work on it though, but if someone submits a PR I'll review it.

**Comment by tonybaloney** [comment]
#179

**Comment by rubik** [comment]
As I merged #179, this issue can finally be closed. Radon now supports reading values from a configuration file, thanks to @tonybaloney. It will be released shortly.
