### ISSUE TITLE
Could not decode an unicode characters

### ISSUE THREAD

**Issue by uetoyo** [rubik/radon#86]
I get this error when using accented letters (ěščřžýáíéó). I can omit them in doc strings, but I have to use them in regexp. Thanks for help!

`ERROR: 'charmap' codec can't decode byte 0x81 in position [...]: character maps to <undefined>`

Note: I have this line at top of the file: `#  -*- coding: utf-8 -*-`

**Comment by rubik** [comment]
I cannot reproduce this. I tried with both Python 2 and 3, and this file was analyzed correctly:
```python
a = 'ěščřžýáíéó'

def f():
    c = 0
    for i in range(34):
        for j in range(42):
            c += i*j
    return c
```

The line at the top of the file is never used by Radon, which always tries to decode the bytes as UTF-8.

**Comment by uetoyo** [comment]
I am sure that encoding is ok. i have problem wit upper case letters:

```
a = 'ĚŠČŘŽÝÁÍÉÓ'

def f():
    c = 0
    for i in range(34):
        for j in range(42):
            c += i*j
    return c
```

`ERROR: 'charmap' codec can't decode byte 0x98 in position 12: character maps to <undefined>`

**Comment by rubik** [comment]
Still cannot reproduce it, sorry. There was another issue like this one some time ago, and after the author changed some local settings (maybe in the terminal?) even he himself couldn't reproduce it.
https://github.com/rubik/radon/issues/72

**Comment by SowingSadness** [comment]
[views.zip](https://github.com/rubik/radon/files/558839/views.zip)

>radon cc views.py -a
views.py
    ERROR: 'charmap' codec can't decode byte 0x98 in position 1786: character maps to <undefined>

This error symbol is "И"
Then i replace the symbol in file this error hidden.

**Comment by rubik** [comment]
@SowingSadness Cannot reproduce, you are probably on Python 2, see #94.

**Comment by wangleixin2017** [comment]
I meet the same problem ,anyone know how to  solve it?
