### ISSUE TITLE
Radon doesn't compute complexity for "async" method (Python 3.5)

### ISSUE THREAD

**Issue by tsunammis** [rubik/radon#90]
Hello,

I discovered that Radon doesn't compute complexity for "async" method.

Example:

```python
def a_func():
    """some code ...
    """

def another_func():
    """some code ...
    """

async def third_function():
    """bla bla bla ...
    """
```

Radon displayed me only the non-async methods like below.

```
search/myfile.py
    F 410:0 a_func - C
    F 27:0 another_func - B
```

The complexity of `third_function` is not computed.

Any idea ?

**Comment by rubik** [comment]
Very interesting. When I first wrote Radon the `async` syntax didn't even exist, so I guess it's being parsed in a different way and the AST ends up different. I'll take a look, thanks.

**Comment by tsunammis** [comment]
Thanks :)

**Comment by rubik** [comment]
Should be fixed now. Please reopen if you find other cases in which radon does not work!

**Comment by tsunammis** [comment]
Thanks a lot, did you update version on pypi ?

**Comment by rubik** [comment]
Yep, version 1.4.0.

**Comment by tsunammis** [comment]
@rubik thanks :)
