### ISSUE TITLE
Doesn't support mypy annotations

### ISSUE THREAD

**Issue by povilasb** [rubik/radon#93]
Sample code snippet:
```
def sum(a: int, b: int) -> int:
    return a + b
```

This is a valid python 3 code.
Running radon `1.4.2` on this code returns me an error:
```
➜  /tmp radon cc test.py    
test.py
    ERROR: invalid syntax (<unknown>, line 1)
```

See: http://www.mypy-lang.org/

**Comment by rubik** [comment]
Cannot reproduce. Are you running radon with Python 2?

**Comment by povilasb** [comment]
Ahh, you're right. I used python 2 interpreter....
