### ISSUE TITLE
no way to ONLY get the summary

### ISSUE THREAD

**Issue by grayaii** [rubik/radon#96]
We have hundreds of files in our project.
The following command prints gobs and gobs of output:
radon raw . -s
I only want the summary, not the details of each file.

**Comment by rubik** [comment]
Truth be told, the summary isn't very useful. If you have hundreds of files, you'll also have hundreds of functions and most of them will be A. So the summary will give you A.

Radon was conceived to detect where in the codebase the code is most complex. So you should run it and filter according to the rank. For example, `radon cc -n C` will output only the blocks with a rank of `C` or higher.

**Comment by grayaii** [comment]
gotcha. makes sense. thanks for quick response!
